apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: led-light-instance-01
  labels:
    description: LEDLight
    model: led-light
spec:
  deviceModelRef:
    name: led-light
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: 'kubernetes.io/hostname'
        operator: In
        values:
        - jetson-edge          #pls give your edge node name
  protocol:
    bluetooth:
      macAddress: "8C:CE:4E:83:25:52"
  propertyVisitors:
  - propertyName: "power-status"
    bluetooth:
      characteristicUUID: ff01
      dataWrite:
        "ON": "0x01"   #Here "ON" refers to the value of the property "temperature-enable" and [1] refers to the corresponding []byte value to be written into the device when the value of temperature-enable is "ON"
        "OFF": "0x00"
status:
  twins:
    - propertyName: power-status